### ISSUE TITLE
BS2 Unit 5 : stacking images

### ISSUE THREAD

**Issue by kfisler** [bootstrapworld/curr#105]
"We know we have to stack images, so you’re going to have to use put-image" -- they end up stacking images because that's what put-image does, so the causality in this sentence doesn't hang together.  

Here, it seems that you're expecting folks to get the stacking part without really having had to work through it (the layers of put image got glossed over a bit before this).  Shouldn't there have been an activity before this that played with different stackings, so that readers could understand the point?

**Comment by Emmay** [comment]
I've done edits to this recently, so just making sure you're looking at the current the-unit files from git and not the ones on the website!

**Comment by kfisler** [comment]
Yes, I pulled just before I started reviewing unit 5 this afternoon

**Comment by Emmay** [comment]
"Drawing the World" moved to Unit 8, wording changed to not mention 'stacking' and make it more clear.

**Comment by schanzer** [comment]
I don't think the problem is that were mentioning "stacking". Kathy's concern is that the causality is reversed: we stack because we use put–image, not the other way around.

**Comment by kfisler** [comment]
Let's say I use images A and B to create image AB.  If A and B end up visually side by side in AB, then "stacking" doesn't really make sense.  So we would be stacking, but it wouldn't look like it.  I don't have a problem with the word stacking.  But our goal isn't to stack.  It is to put-image, which happens to stack.

If you want me to look at the current actual wording, let me know.

**Comment by Emmay** [comment]
I would like a review of the current wording: we first cover put-image in Unit 4, and again in Unit 8 for drawing the world.

**Comment by schanzer** [comment]
But what is the _operation_ for image-joining that you use here? Whatever verb you use should work whether the images overlap or not, and overlapping is going to require stacking.

**Comment by gregory-marton** [comment]
One analogy that would be fun and easy to use with physical props in a
classroom would be stickers: put-image sticks/pastes/glues one image on top
of another at a particular place.

Kathi, I'm not seeing how you can get put-image to take only two things and
put them side by side, because it crops the part of the top image that
doesn't fit on the bottom one:

(define tall (rectangle 10 20 "solid" "blue"))
(define wide (rectangle 20 10 "solid" "green"))
(put-image tall 20 10 wide)
[image: Inline image 1]
With three of them, a big background and two smaller things like a player
and danger, they can end up side by side of course, but that works with the
sticker analogy: You pasted one sticker on the background, then you pasted
the other one one the background-and-first-sticker thing.

Does that help?

On Wed, Jun 8, 2016 at 11:53 AM, Emmanuel Schanzer <notifications@github.com

**Comment by schanzer** [comment]
Our language enforces ordering, which means one image always goes first. Since images may overlap, and we don't blend the pixels when this happens, there's an implied stacking order. I strongly suggest leaving the stacking term in there, as well as the emphasis on "we know we'll have to".

**Comment by schanzer** [comment]
@kfisler - sorry to bug you, but Emma and I need to finalize this for CSPdWeek by Friday. Can you review the thread, and Emma's new wording, and see what you think? Are you persuaded by @gregory-marton  and I? If not, do Emma's changes solve the issue?

**Comment by kfisler** [comment]
I think the current wording is fine.  I was thinking of (what I remember of) the DrRacket implementation of put-image that did not involve cropping.  The main issue was the causality wording anyway.  Fine to resolve this.
