### ISSUE TITLE
BS2 Unit 7 : end of Protecting the Boundaries lesson

### ISSUE THREAD

**Issue by kfisler** [bootstrapworld/curr#111]
What if the dog and coin are both at boundaries at the same time?  I fully expect someone is going to ask about that (and they should, as it shows they really understand how the ask works).  This likely warrants a teacher note so they aren't scrambling to find an answer.  It could also be an activity, asking students what the result would be on an example in which both reach the boundaries at once.

**Comment by Emmay** [comment]
This lesson is already quite long, so I'm leaning toward adding this as a teacher note. @schanzer Any preferences for an activity over (or in addition to) a teacher note about this?

**Comment by schanzer** [comment]
Teachers note. In 10 years of teaching this, not a single student or teacher has ever asked about it.

**Comment by Emmay** [comment]
Possible wording. What do you think?

Students may ask: “what happens if the dog and coin reach the boundaries at the same time?” The computer reads each ask branch one at a time, so whichever true condition is listed first in their code will be evaluated first (and the world changed accordingly). On the next tick, next-world runs again, still evaluating the first true statement. If the first ask branch checks only the dog’s x-coordinate, and the dog and coin reach the boundaries at the same time, the dog’s position will be updated slightly before the coin’s, but fast enough to be almost imperceptible to most game players.

To determine for themselves what should happen in this case, students can write another condition to check if the dog is off the right side of the screen AND the coin is off the left side at the same time, but this is optional.

**Comment by schanzer** [comment]
Good, but too much detail for a teacher's note. Here's a tighter version:

What happens if the dog and coin reach the boundaries at the same time? The computer reads `ask` branches _in order_, so it will evaluate the first true condition and change the `world` accordingly. If the first `ask` branch checks only the dog’s x-coordinate, and the dog and coin reach the boundaries at the same time, the dog’s position will be updated one (mostly-imperceptible) frame before the coin’s.

Optional challenge exercise: write another condition to check if the dog AND the coin are off the screen at the same time.

**Comment by Emmay** [comment]
Sounds great. Just pushed this change to the new branch!
