### ISSUE TITLE
BS2 Unit 9 : "shoots a projectile" in teacher notes

### ISSUE THREAD

**Issue by kfisler** [bootstrapworld/curr#113]
Can we come up with an description that isn't shooting a projectile?  Just trying to avoid language that turns people away from game programming

**Comment by Emmay** [comment]
This is part of a list of suggestions for game components. It motivates: "An element of the world cannot be taken out of the world struct, but its location can be changed so that it no longer appears on the screen. If the DOG-IMG has been set to a certain coordinate and has been "destroyed", should it continue to move normally?"

How about: "A barrier disappears once enough coins have been collected: An element of the world cannot be taken out...."

This section now occurs in Unit 9, where students are already well into making their game. Not sure how far we want to skirt away from projectiles at this stage, since many students will want some variation on something getting hit and disappearing from the game screen.

**Comment by schanzer** [comment]
Leaving projectiles as part of a _list of options_ is perfectly reasonable in Unit 9.

**Comment by kfisler** [comment]
I'm still wary of falling back on this unless necessary.  For example, somewhere in the notes we might say "if your student wants to write a game with projectiles, you capture them with X".  But here we are just looking for an example. We should do better than to fall back on metaphors that raise alarms.

In this specific case, I don't even see why a reference to projectiles is needed.  Doesn't it work just as well to say "The player destroys the alien/shark/bad-guy by making it collide with another game element" -- removes "shoot" and "projectile" without diluting the principle.

I really, really want to avoid "shoots" unless necessary -- these words can strike people hard, especially after events of gun violence. You really want someone seeing this just after an event like Orlando, for example?

**Comment by schanzer** [comment]
[Renamed topic for clarity]
Good point - okay, so "shoot" is definitely on the no-no list. Projectile seems more usable, but I can be convinced otherwise. How about this: "The player fires an arrow at a dragon"

**Comment by Emmay** [comment]
New wording: "The player destroys the dragon/alien/bad guy by firing an arrow/laser/other projectile: An element of the world cannot be taken out of the World..."

**Comment by schanzer** [comment]
👍  Love it. Emma, close when ready. :)
