### ISSUE TITLE
BS2: Page 17 and 18 must be together when workbook is open

### ISSUE THREAD

**Issue by Emmay** [bootstrapworld/curr#132]
Goal of these pages is to keep track of the things that move independently

**Comment by Emmay** [comment]
Fixed this and some other formatting issues by combining 2 notes pages ("Lesson 4+5") since there are no workbook pages for unit 4.

**Comment by schanzer** [comment]
I know you're going to kill me for this, but I'm always a fan of giving people more space to write, and it's weird to have a page suddenly count for two lessons. 

Rather than dropping a page to make 17+18 line up, how about we _add_ one instead? Might I suggest adding an extra page at the beginning of the document, inside the front cover? You can copy what we do for BS:1 (putting your name first!).

Also - shouldn't we move the contract pages to the back, to match BS:1? I'll open a separate issue for that.

**Comment by Emmay** [comment]
Can do. Do you have a Word doc of the acknowledgements page?
