### ISSUE TITLE
BS2, unit 4, Event-based programming

### ISSUE THREAD

**Issue by kfisler** [bootstrapworld/curr#150]
Quoting end of unit 4: "big-bang and The Hollywood Principle are all part of a programming paradigm used all over the world, called Event-Based Programming."

I need to check with Shriram -- I don't think this statement is entirely accurate.  Event-based programming typically refers to user-generated events, not system-generated events.  I think the accurate term here is "model-view-controller architecture".  But let me see what Shriram says.

I understand the tight time constraint.  Writing to him now.

**Comment by gregory-marton** [comment]
Event-driven programming has always included system-generated events. In
some sense those are also user-generated, in that the user has asked the
system to do its thing.
http://openbookproject.net/thinkcs/python/english3e/events.html
Historical:
http://columbus.exp.sis.pitt.edu/socialreader/readings/books/lewis/6-3.html

Re: MVC, I think this explanation is a good one as to why that's not it:
http://c2.com/cgi/wiki?MvcVersusEventDriven

> How does a ModelViewController GUI system differ from an
>> EventDrivenProgramming-based model?
>
> Apples and oranges. MVC describes large scale structure,
> EventDrivenProgramming describes how flow is controlled. One can use both
> simultaneously.
>

[In many MVC deployments,]

> Events don't really control the flow, other than requesting actions, such
> as asking to open a new form window. Perhaps you are suggesting that the
> underlying framework, the one that is often hidden explicity or implicitly
> from event-filling application developer, can be made with MVC. In
> EventDrivenProgramming, an application developer does not concern
> themselves with the "controller" code. That is an implementation detail
> that is expected be abstracted away. MVC implies that they should be on
> equal footing.


Bootstrap students likewise concern themselves not at all with the
controller, but focus on the model (world) and what to do with each single
event.

So I think the statement is accurate, though I prefer "event-driven" to
"event-based" because it's slightly more descriptive, and also apparently
more widely used.

Grem

**Comment by kfisler** [comment]
Shriram is okay with the wording as is.  Either event-driven or event-based would be fine (I don't think either is harder or easier than the other).

**Comment by schanzer** [comment]
Let's let marketing be the tiebreaker: which term is more commonly known?

**Comment by kfisler** [comment]
In our audience, neither one is known at all.  We have enough else going on, so why don't we just leave the current term as is and work on stuff that might matter more.

**Comment by kfisler** [comment]
Actually, Shriram wants a wording addition after all.  He wants to add

“(This is also closely related to the Model-View-Controller pattern used to build professional systems.)” Looks like this should go at the end of the first sentence, where you define event-based programming.

**Comment by schanzer** [comment]
Added in ee45e6df1f5bc826c14f9a65aba16e96c60ff447
