### ISSUE TITLE
Why are Scoring and Levels in the same unit?

### ISSUE THREAD

**Issue by kfisler** [bootstrapworld/curr#170]
They seem like different mix-and-match features that someone might want (and scoring is easier given that it has fewer impacts on the code).  Why the decision to lump them together rather than make separate segments from them?

**Comment by Emmay** [comment]
This is a holdout from the previous iteration, when scoring and levels were a supplemental unit together. Since we're using the score to determine the levels in this example, I think it still makes sense to have them together in the track, but if we think we want more segments in general, we could separate them.

**Comment by kfisler** [comment]
I think we should separate them, with a note in the title for the Levels unit that it builds on Scoring.  Some people will want to add Scores without Levels.

A proper "prereq" infrastructure would be nice, but not feasible in the short term.  

(my grades are finally in so I'm able to work on this again ...)
