### ISSUE TITLE
Unit 2 : Cakes image doesn't make sense now

### ISSUE THREAD

**Issue by kfisler** [bootstrapworld/curr#183]
Now that the data structure has been reduced to not include the message, does the picture of the cake make sense?  It isn't clear what the picture illustrates now (would be okay if we took the message off though)

**Comment by Emmay** [comment]
I kept these in initially just to have some images to break up the text. Since students no longer draw cakes at all, is it necessary that the images stay true to what they *would* draw? Would it be better to re-create these images without the messages, or just find some generic images of cakes online?

**Comment by schanzer** [comment]
I'd go generic. It's faster for you and more visually-appealing for them. :)
