### ISSUE TITLE
Levels unit -- "next condition to check" code shows as first condition

### ISSUE THREAD

**Issue by kfisler** [bootstrapworld/curr#207]
There's an activity in the levels unit that says "After checking whether or not the game is over, what is the next condition to check?"

The code immediately after that has a function that starts with an if on the g.score value.  WIth the if being the first thing in the function, the score has become the first thing to check, not the "next".  So the language and the code aren't consistent.

Also, is the "game over" decision part of the state (in that state doesn't change after that) or part of drawing?  If it is part of state, then "next condition" makes no sense anyway.

**Comment by Emmay** [comment]
I think this may have been changed in a previous edit, because I'm not seeing this in either the scoring or levels feature.  Scoring now has text that says: " After checking whether our game over condition is met (more on this shortly), the next three conditions in our @code{next-state-tick} function check whether the player has collided with the danger and target, as well as whether the player is jumping on the danger:" Which is exactly what the code shows. 

Might be able to close this now.
