### ISSUE TITLE
[DS - Unit 2] Do we need CPO in Unit 2?

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curr#250]
Do we even need to use CPO here? All they're doing is looking at spreadsheets - why not keep them in google sheets?

I'm not explicitly advocating this, mind you -- rather, is there *anything* we can do to make our use of CPO a value-add here?

**Comment by SDooman** [comment]
@schanzer 

In the beginning, Unit 2 was laid out to have students start in Google Sheets, answer questions with that software, and finish the unit by typing the word `presidents` into the interactions window.

The converse argument to this one was:
 - Students haven't necessarily seen Google Sheets before this.  Having students learn to navigate Google Sheets seems unnecessary if they can see the data at the interactions window, especially since they will need to display tables at the interactions window in every unit.

**Comment by schanzer** [comment]
I'm convinced. :)
