### ISSUE TITLE
[DS] Series isn't a good name

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curr#296]
The workshop ground to a halt for about 20min, as teachers struggled to wrap their heads around the idea of a `series`. It's already a term with meaning in the math world, and there's way too much negative transfer. One teachers said "if all of these are plots, and there's a function called _draw-plot_, why shouldn't the type just be _plot_?"

**Comment by blerner** [comment]
Counterargument: https://support.office.com/en-us/article/Create-a-chart-from-start-to-finish-0baf399e-dd61-4e18-8a73-b3fd5d5680c2.  "Data series" is the term we wanted to transfer, so that teachers & students could carry over their understanding to Excel/other spreadsheet tools.

A plot is the rendering of the underlying data series.  They are two distinct things.

**Comment by schanzer** [comment]
I agree that Plot is not the best term, for exactly the reason you describe. I also think "data series", while a proper technical term, isn't necessarily right either. I can't think of a better one at the moment, mind you. :)

**Comment by schanzer** [comment]
@sorawee @blerner how painful is it to change this from "Series" to "Data Series"? I know there's error message work and type info to change, and this is a pretty low priority. If this is anything more than trivial, I say we stick with Series and close the issue.

**Comment by sorawee** [comment]
That's already done in https://github.com/brownplt/code.pyret.org/pull/225. Please review and if it looks good, we can get it merged.

**Comment by schanzer** [comment]
Closed by 54d58340e20f7a8eaf2cc48058fd48e19a4b1a78 and  d3d895930b6ff6f887e76229b669ac1fd2d508dc.
