### ISSUE TITLE
build.rkt Breaks When Using Racket 7.0

### ISSUE THREAD

**Issue by doshiro** [bootstrapworld/curr#423]
I'm unsure of the cause of this issue, however running `racket build.rkt` on Racket 7.0 results in the following error when building `courses/*/units/langs/*/the-unit.scrbl`:

```
build.rkt: Building /home/travis/build/doshiro/curr/courses/algebra-pyret/units/langs/en-us/Supplemental/the-unit.scrbl  
building exercise at: application: not a procedure;  
 expected a procedure that can be applied to arguments  
  given: #f  
  arguments...:  
   #f  
   '("NOTE: THESE LESSONS ARE NOT INTENDED TO BE TAUGHT IN SEQUENCE - they are collected here solely for convenience!" "\n" "S...   
  context...:  
   "/home/travis/build/doshiro/curr/courses/algebra-pyret/units/langs/en-us/Supplemental/the-unit.scrbl": [running body]  
   for-loop   
   run-module-instance!125  
   do-dynamic-require5  
   /home/travis/build/doshiro/curr/build.rkt:77:0: run-scribble8  
   /home/travis/build/doshiro/curr/build.rkt:292:8: for-loop  
   /home/travis/build/doshiro/curr/build.rkt:286:6: for-loop  
   /home/travis/build/doshiro/curr/build.rkt:281:0: build-course-units  
   /home/travis/build/doshiro/curr/build.rkt:699:6: for-loop  
   /home/travis/build/doshiro/curr/build.rkt:693:0: for-loop  
   "/home/travis/build/doshiro/curr/build.rkt": [running body]  
   for-loop  
   run-module-instance!125  
   perform-require!78
```  

Versions 6.12 and below seem to be fine. Just putting this out there for anyone who upgrades their version of Racket and suddenly runs into problems.

**Comment by schanzer** [comment]
Paging @ds26gte - can you look into this?

**Comment by ds26gte** [comment]
@schanzer, I'll look into it, but as a reminder, this is the same problem that I ran into for which I asked for logs from you and @kfisler around Aug 15, since neither of you were hit by the bug. Looking at the latter's log, I noted that she was using Racket v6.12, not v7 as I was.

There seems to have been a change in how syntax-parameters (~= symbols as macros) work between Racket v6.12 and v7, but I couldn't find it documented. Our use of the syntax-parameter `current-the-unit-description` seems to trip this somehow (i.e., it's set to something useful in v6.12, but `#f` in v7). Maybe because this is a syntax phase issue, instrumenting when something is happening didn't help at all at the time, hence my decision to downgrade to v6.12 for the time being.

**Comment by blerner** [comment]
@ds26gte I pinged folks on the Racket slack, and Sam mentioned https://github.com/racket/racket/issues/2035 and confirmed that he's pretty sure syntax-parameters did change in 7.0

**Comment by blerner** [comment]
Further follow-up from Matthew: "Offhand, it looks like a problem with syntax transformers and `set!` – probably a bug in the expander, although it’s possibly in syntax parameters. The expanded code has `(#%app the-unit-description the-unit-description ....)`, and I think it was supposed to be `(set! the-unit-description ....)`."

Probably worth following up with him offline from this bug, until we know what's going on and how to fix it.

**Comment by mflatt** [comment]
Yes, this seems to be a bug in `syntax-parameterize`. Specifically, it looks like a missing `(require (for-template '#%kernel))` in “stxparamkey.rkt”  to make an identifier-binding comparsion on `set!` work as intended. I should be able to push a repair (for the next release) later today.

**Comment by schanzer** [comment]
Thanks @mflatt and @blerner !!

**Comment by schanzer** [comment]
@doshiro is this still an issue for you?
